"""Abstract repository interfaces (ports).

These interfaces define the contract between the application layer and the
persistence layer. They are framework-agnostic: implementations live in
`app.repositories` and are injected via the DI container.

Each repository is an `async` repository because the persistence layer is
asynchronous (SQLAlchemy 2.0 async over psycopg).
"""

import builtins
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities.facility import PrimaryHealthCentre, Warehouse
from app.domain.entities.intelligence import ColdAlert, Prediction, WeatherSnapshot
from app.domain.entities.logistics import ColdContainer, Driver, Vehicle
from app.domain.entities.role import Role
from app.domain.entities.route import Route, Waypoint
from app.domain.entities.shipment import Shipment
from app.domain.entities.user import User


class HealthRepository(Protocol):
    """Persistence contract used by the health check."""

    async def ping(self) -> bool: ...


class RoleRepository(Protocol):
    async def create(self, entity: Role) -> Role: ...
    async def get(self, role_id: UUID) -> Role | None: ...
    async def get_by_name(self, name: str) -> Role | None: ...
    async def list(self, include_deleted: bool = False) -> list[Role]: ...
    async def soft_delete(self, role_id: UUID) -> Role | None: ...
    async def get_roles_for_user(self, user_id: UUID) -> builtins.list[Role]: ...


class UserRepository(Protocol):
    async def create(self, entity: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list(self) -> list[User]: ...
    async def update(self, entity: User) -> User: ...
    async def count(
        self,
        *,
        search: str | None = None,
        role: str | None = None,
        is_active: bool | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        role: str | None = None,
        is_active: bool | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[User]: ...


class RefreshTokenRepository(Protocol):
    async def create(
        self, user_id: UUID, token_hash: str, expires_at: datetime
    ) -> None: ...
    async def revoke(self, token_hash: str) -> None: ...
    async def is_valid(self, token_hash: str) -> bool: ...
    async def get_user_id(self, token_hash: str) -> UUID | None: ...


class WarehouseRepository(Protocol):
    async def create(self, entity: Warehouse) -> Warehouse: ...
    async def get(self, warehouse_id: UUID) -> Warehouse | None: ...
    async def list(self) -> list[Warehouse]: ...


class PhCentreRepository(Protocol):
    async def create(self, entity: PrimaryHealthCentre) -> PrimaryHealthCentre: ...
    async def get(self, phc_id: UUID) -> PrimaryHealthCentre | None: ...
    async def list(self) -> list[PrimaryHealthCentre]: ...


class DriverRepository(Protocol):
    async def create(self, entity: Driver) -> Driver: ...
    async def get(self, driver_id: UUID) -> Driver | None: ...
    async def list(self) -> list[Driver]: ...


class VehicleRepository(Protocol):
    async def create(self, entity: Vehicle) -> Vehicle: ...
    async def get(self, vehicle_id: UUID) -> Vehicle | None: ...
    async def list(self) -> list[Vehicle]: ...


class ContainerRepository(Protocol):
    async def create(self, entity: ColdContainer) -> ColdContainer: ...
    async def get(self, container_id: UUID) -> ColdContainer | None: ...
    async def list(self) -> list[ColdContainer]: ...
    async def update(self, entity: ColdContainer) -> ColdContainer: ...


class ShipmentRepository(Protocol):
    async def create(self, entity: Shipment) -> Shipment: ...
    async def get(self, shipment_id: UUID) -> Shipment | None: ...
    async def list(self) -> list[Shipment]: ...
    async def update(self, entity: Shipment) -> Shipment: ...


class RouteRepository(Protocol):
    async def create(self, entity: Route) -> Route: ...
    async def get(self, route_id: UUID) -> Route | None: ...
    async def list_for_shipment(self, shipment_id: UUID) -> list[Route]: ...
    async def update(self, entity: Route) -> Route: ...


class WaypointRepository(Protocol):
    async def create(self, entity: Waypoint) -> Waypoint: ...
    async def list_for_route(self, route_id: UUID) -> list[Waypoint]: ...
    async def update(self, entity: Waypoint) -> Waypoint: ...


class PredictionRepository(Protocol):
    async def create(self, entity: Prediction) -> Prediction: ...
    async def latest_for_shipment(self, shipment_id: UUID) -> Prediction | None: ...


class WeatherCacheRepository(Protocol):
    async def get(self, latitude: float, longitude: float) -> WeatherSnapshot | None: ...
    async def upsert(self, snapshot: WeatherSnapshot) -> None: ...


class AlertRepository(Protocol):
    async def create(self, entity: ColdAlert) -> ColdAlert: ...
    async def list(self, status: str | None = None) -> list[ColdAlert]: ...
    async def acknowledge(self, alert_id: UUID, user_id: UUID) -> ColdAlert | None: ...
