"""Abstract repository interfaces (ports).

These interfaces define the contract between the application layer and the
persistence layer. They are framework-agnostic: implementations live in
`app.repositories` and are injected via the DI container.

Each repository is an `async` repository because the persistence layer is
asynchronous (SQLAlchemy 2.0 async over psycopg).
"""

import builtins
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities.facility import PrimaryHealthCentre, Warehouse
from app.domain.entities.intelligence import ColdAlert, Prediction, WeatherSnapshot
from app.domain.entities.logistics import ColdContainer, Driver, Vehicle
from app.domain.entities.role import Role
from app.domain.entities.route import Route, Waypoint
from app.domain.entities.shipment import Shipment
from app.domain.entities.user import User


class HealthRepository(Protocol):
    """Persistence contract used by the health check."""

    async def ping(self) -> bool: ...


class RoleRepository(Protocol):
    async def create(self, entity: Role) -> Role: ...
    async def get(self, role_id: UUID) -> Role | None: ...
    async def get_by_name(self, name: str) -> Role | None: ...
    async def list(self, include_deleted: bool = False) -> list[Role]: ...
    async def soft_delete(self, role_id: UUID) -> Role | None: ...
    async def get_roles_for_user(self, user_id: UUID) -> builtins.list[Role]: ...


class UserRepository(Protocol):
    async def create(self, entity: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list(self) -> list[User]: ...
    async def update(self, entity: User) -> User: ...
    async def count(
        self,
        *,
        search: str | None = None,
        role: str | None = None,
        is_active: bool | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        role: str | None = None,
        is_active: bool | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[User]: ...


class RefreshTokenRepository(Protocol):
    async def create(
        self, user_id: UUID, token_hash: str, expires_at: datetime
    ) -> None: ...
    async def revoke(self, token_hash: str) -> None: ...
    async def is_valid(self, token_hash: str) -> bool: ...
    async def get_user_id(self, token_hash: str) -> UUID | None: ...


class WarehouseRepository(Protocol):
    async def create(self, entity: Warehouse) -> Warehouse: ...
    async def get(self, warehouse_id: UUID) -> Warehouse | None: ...
    async def list(self) -> builtins.list[Warehouse]: ...
    async def get_by_code(self, code: str) -> Warehouse | None: ...
    async def update(self, entity: Warehouse) -> Warehouse: ...
    async def count(
        self,
        *,
        search: str | None = None,
        capacity_min: int | None = None,
        capacity_max: int | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        capacity_min: int | None = None,
        capacity_max: int | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[Warehouse]: ...
    async def soft_delete(self, warehouse_id: UUID) -> Warehouse | None: ...


class PhCentreRepository(Protocol):
    async def create(self, entity: PrimaryHealthCentre) -> PrimaryHealthCentre: ...
    async def get(self, phc_id: UUID) -> PrimaryHealthCentre | None: ...
    async def list(self) -> builtins.list[PrimaryHealthCentre]: ...
    async def get_by_code(self, code: str) -> PrimaryHealthCentre | None: ...
    async def update(self, entity: PrimaryHealthCentre) -> PrimaryHealthCentre: ...
    async def count(
        self,
        *,
        search: str | None = None,
        state: str | None = None,
        capacity_min: int | None = None,
        capacity_max: int | None = None,
        priority_level: int | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        state: str | None = None,
        capacity_min: int | None = None,
        capacity_max: int | None = None,
        priority_level: int | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[PrimaryHealthCentre]: ...
    async def soft_delete(self, phc_id: UUID) -> PrimaryHealthCentre | None: ...


class DriverRepository(Protocol):
    async def create(self, entity: Driver) -> Driver: ...
    async def get(self, driver_id: UUID) -> Driver | None: ...
    async def get_by_phone(self, phone: str) -> Driver | None: ...
    async def get_by_license(self, license_number: str) -> Driver | None: ...
    async def get_assigned_driver(self, vehicle_id: UUID) -> Driver | None: ...
    async def update(self, entity: Driver) -> Driver: ...
    async def list(self) -> builtins.list[Driver]: ...
    async def count(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[Driver]: ...
    async def soft_delete(self, driver_id: UUID) -> Driver | None: ...


class VehicleRepository(Protocol):
    async def create(self, entity: Vehicle) -> Vehicle: ...
    async def get(self, vehicle_id: UUID) -> Vehicle | None: ...
    async def get_by_registration(self, registration_number: str) -> Vehicle | None: ...
    async def update(self, entity: Vehicle) -> Vehicle: ...
    async def list(self) -> builtins.list[Vehicle]: ...
    async def count(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
        vehicle_type: str | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
        vehicle_type: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[Vehicle]: ...
    async def soft_delete(self, vehicle_id: UUID) -> Vehicle | None: ...


class ContainerRepository(Protocol):
    async def create(self, entity: ColdContainer) -> ColdContainer: ...
    async def get(self, container_id: UUID) -> ColdContainer | None: ...
    async def list(self) -> list[ColdContainer]: ...
    async def update(self, entity: ColdContainer) -> ColdContainer: ...


class ShipmentRepository(Protocol):
    async def create(self, entity: Shipment) -> Shipment: ...
    async def get(self, shipment_id: UUID) -> Shipment | None: ...
    async def get_by_tracking_code(self, tracking_code: str) -> Shipment | None: ...
    async def list(self) -> builtins.list[Shipment]: ...
    async def update(self, entity: Shipment) -> Shipment: ...
    async def count(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
        priority: str | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        search: str | None = None,
        status: str | None = None,
        priority: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[Shipment]: ...
    async def soft_delete(self, shipment_id: UUID) -> Shipment | None: ...


class RouteRepository(Protocol):
    async def create(self, entity: Route) -> Route: ...
    async def get(self, route_id: UUID) -> Route | None: ...
    async def list_for_shipment(self, shipment_id: UUID) -> list[Route]: ...
    async def update(self, entity: Route) -> Route: ...
    async def count(
        self,
        *,
        shipment_id: UUID | None = None,
        status: str | None = None,
        is_selected: bool | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        shipment_id: UUID | None = None,
        status: str | None = None,
        is_selected: bool | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> list[Route]: ...
    async def soft_delete(self, route_id: UUID) -> Route | None: ...


class WaypointRepository(Protocol):
    async def create(self, entity: Waypoint) -> Waypoint: ...
    async def get(self, waypoint_id: UUID) -> Waypoint | None: ...
    async def list_for_route(self, route_id: UUID) -> list[Waypoint]: ...
    async def update(self, entity: Waypoint) -> Waypoint: ...
    async def delete(self, waypoint_id: UUID) -> Waypoint | None: ...


class PredictionRepository(Protocol):
    async def create(self, entity: Prediction) -> Prediction: ...
    async def get(self, prediction_id: UUID) -> Prediction | None: ...
    async def list_for_shipment(self, shipment_id: UUID) -> list[Prediction]: ...
    async def latest_for_shipment(self, shipment_id: UUID) -> Prediction | None: ...
    async def count(
        self,
        *,
        shipment_id: UUID | None = None,
        risk_level: str | None = None,
        model_version: str | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        shipment_id: UUID | None = None,
        risk_level: str | None = None,
        model_version: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> list[Prediction]: ...
    async def update(self, entity: Prediction) -> Prediction: ...
    async def delete(self, prediction_id: UUID) -> Prediction | None: ...


class WeatherCacheRepository(Protocol):
    async def get(self, latitude: float, longitude: float) -> WeatherSnapshot | None: ...
    async def upsert(self, snapshot: WeatherSnapshot) -> None: ...


class AlertRepository(Protocol):
    async def create(self, entity: ColdAlert) -> ColdAlert: ...
    async def get(self, alert_id: UUID) -> ColdAlert | None: ...
    async def list(self, status: str | None = None) -> builtins.list[ColdAlert]: ...
    async def list_for_shipment(self, shipment_id: UUID) -> builtins.list[ColdAlert]: ...
    async def count(
        self,
        *,
        shipment_id: UUID | None = None,
        container_id: UUID | None = None,
        severity: str | None = None,
        status: str | None = None,
    ) -> int: ...
    async def list_paginated(
        self,
        *,
        shipment_id: UUID | None = None,
        container_id: UUID | None = None,
        severity: str | None = None,
        status: str | None = None,
        offset: int = 0,
        limit: int = 20,
    ) -> builtins.list[ColdAlert]: ...
    async def update(self, entity: ColdAlert) -> ColdAlert: ...
    async def acknowledge(self, alert_id: UUID, user_id: UUID) -> ColdAlert | None: ...
    async def delete(self, alert_id: UUID) -> ColdAlert | None: ...
