"""create initial schema

Autogenerated from ORM metadata: creates all application tables.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-07
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    enum_type = sa.Enum('super_admin', 'admin', 'dispatcher', 'logistics', 'driver', name="user_role")
    enum_type.create(op.get_bind(), checkfirst=True)
    op.execute(sa.text("""

CREATE TABLE cold_containers (
	id UUID NOT NULL, 
	asset_tag VARCHAR(64) NOT NULL, 
	temperature_setpoint FLOAT NOT NULL, 
	min_temperature FLOAT NOT NULL, 
	max_temperature FLOAT NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	current_latitude FLOAT, 
	current_longitude FLOAT, 
	battery_level INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
)

"""))
    op.execute(sa.text("""

CREATE TABLE primary_health_centres (
	id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	code VARCHAR(32) NOT NULL, 
	district VARCHAR(128) NOT NULL, 
	state VARCHAR(128) NOT NULL, 
	latitude FLOAT NOT NULL, 
	longitude FLOAT NOT NULL, 
	contact VARCHAR(64) NOT NULL, 
	capacity INTEGER NOT NULL, 
	priority_level INTEGER NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_phcs_latitude CHECK (latitude BETWEEN -90 AND 90), 
	CONSTRAINT ck_phcs_longitude CHECK (longitude BETWEEN -180 AND 180), 
	CONSTRAINT ck_phcs_capacity CHECK (capacity >= 0), 
	CONSTRAINT ck_phcs_priority_level CHECK (priority_level BETWEEN 1 AND 10)
)

"""))
    op.execute(sa.text("""

CREATE TABLE roles (
	id UUID NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	is_deleted BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
)

"""))
    op.execute(sa.text("""

CREATE TABLE users (
	id UUID NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	full_name VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	role user_role NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	is_deleted BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
)

"""))
    op.execute(sa.text("""

CREATE TABLE vehicles (
	id UUID NOT NULL, 
	registration_number VARCHAR(32) NOT NULL, 
	vehicle_type VARCHAR(32) NOT NULL, 
	capacity_kg INTEGER NOT NULL, 
	is_reefer BOOLEAN NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	maintenance_status VARCHAR(24) NOT NULL, 
	last_maintenance_at TIMESTAMP WITH TIME ZONE, 
	next_maintenance_due_at TIMESTAMP WITH TIME ZONE, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_vehicles_capacity_kg CHECK (capacity_kg >= 0), 
	CONSTRAINT ck_vehicles_status CHECK (status IN ('active', 'maintenance', 'retired')), 
	CONSTRAINT ck_vehicles_maintenance_status CHECK (maintenance_status IN ('ok', 'scheduled', 'in_progress', 'overdue'))
)

"""))
    op.execute(sa.text("""

CREATE TABLE warehouses (
	id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	code VARCHAR(32) NOT NULL, 
	latitude FLOAT NOT NULL, 
	longitude FLOAT NOT NULL, 
	address VARCHAR(500) NOT NULL, 
	capacity INTEGER NOT NULL, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_warehouses_latitude CHECK (latitude BETWEEN -90 AND 90), 
	CONSTRAINT ck_warehouses_longitude CHECK (longitude BETWEEN -180 AND 180), 
	CONSTRAINT ck_warehouses_capacity CHECK (capacity >= 0)
)

"""))
    op.execute(sa.text("""

CREATE TABLE weather_cache (
	id UUID NOT NULL, 
	latitude FLOAT NOT NULL, 
	longitude FLOAT NOT NULL, 
	temperature_c FLOAT NOT NULL, 
	precipitation_mm FLOAT NOT NULL, 
	wind_kmh FLOAT NOT NULL, 
	humidity_pct FLOAT NOT NULL, 
	condition VARCHAR(64) NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	forecast JSON NOT NULL, 
	is_mock BOOLEAN NOT NULL, 
	fetched_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_weather_lat_lon UNIQUE (latitude, longitude)
)

"""))
    op.execute(sa.text("""

CREATE TABLE drivers (
	id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	phone VARCHAR(32) NOT NULL, 
	license_number VARCHAR(64) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	vehicle_id UUID, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_drivers_status CHECK (status IN ('available', 'assigned', 'on_leave')), 
	CONSTRAINT ck_drivers_phone_length CHECK (length(phone) BETWEEN 10 AND 15), 
	FOREIGN KEY(vehicle_id) REFERENCES vehicles (id) ON DELETE SET NULL
)

"""))
    op.execute(sa.text("""

CREATE TABLE refresh_tokens (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	token_hash VARCHAR(128) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
)

"""))
    op.execute(sa.text("""

CREATE TABLE user_roles (
	user_id UUID NOT NULL, 
	role_id UUID NOT NULL, 
	PRIMARY KEY (user_id, role_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE
)

"""))
    op.execute(sa.text("""

CREATE TABLE shipments (
	id UUID NOT NULL, 
	tracking_code VARCHAR(64) NOT NULL, 
	vaccine_name VARCHAR(255) NOT NULL, 
	dose_count INTEGER NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	temperature_min FLOAT NOT NULL, 
	temperature_max FLOAT NOT NULL, 
	warehouse_id UUID NOT NULL, 
	destination_id UUID NOT NULL, 
	container_id UUID, 
	driver_id UUID, 
	status VARCHAR(24) NOT NULL, 
	dispatched_at TIMESTAMP WITH TIME ZONE, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	estimated_delivery_at TIMESTAMP WITH TIME ZONE, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_shipments_dose_count CHECK (dose_count >= 0), 
	CONSTRAINT ck_shipments_temperature_range CHECK (temperature_min < temperature_max), 
	CONSTRAINT ck_shipments_status CHECK (status IN ('created', 'predicted', 'dispatched', 'in_transit', 'delivered', 'cancelled')), 
	CONSTRAINT ck_shipments_priority CHECK (priority IN ('high', 'medium', 'low')), 
	FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT, 
	FOREIGN KEY(destination_id) REFERENCES primary_health_centres (id) ON DELETE RESTRICT, 
	FOREIGN KEY(container_id) REFERENCES cold_containers (id) ON DELETE SET NULL, 
	FOREIGN KEY(driver_id) REFERENCES drivers (id) ON DELETE SET NULL
)

"""))
    op.execute(sa.text("""

CREATE TABLE cold_alerts (
	id UUID NOT NULL, 
	shipment_id UUID, 
	container_id UUID, 
	severity VARCHAR(16) NOT NULL, 
	alert_type VARCHAR(64) NOT NULL, 
	message TEXT NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	acknowledged_by UUID, 
	acknowledged_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(shipment_id) REFERENCES shipments (id) ON DELETE CASCADE, 
	FOREIGN KEY(container_id) REFERENCES cold_containers (id) ON DELETE CASCADE, 
	FOREIGN KEY(acknowledged_by) REFERENCES users (id) ON DELETE SET NULL
)

"""))
    op.execute(sa.text("""

CREATE TABLE predictions (
	id UUID NOT NULL, 
	shipment_id UUID NOT NULL, 
	excursion_risk FLOAT NOT NULL, 
	risk_level VARCHAR(16) NOT NULL, 
	confidence FLOAT NOT NULL, 
	expected_min_temp FLOAT NOT NULL, 
	expected_max_temp FLOAT NOT NULL, 
	model_version VARCHAR(64) NOT NULL, 
	features JSON NOT NULL, 
	explanations JSON NOT NULL, 
	valid_until TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(shipment_id) REFERENCES shipments (id) ON DELETE CASCADE
)

"""))
    op.execute(sa.text("""

CREATE TABLE routes (
	id UUID NOT NULL, 
	shipment_id UUID NOT NULL, 
	distance_km FLOAT NOT NULL, 
	duration_minutes INTEGER NOT NULL, 
	stops JSON NOT NULL, 
	polyline VARCHAR(1000) NOT NULL, 
	weather_factor FLOAT NOT NULL, 
	safety_score FLOAT NOT NULL, 
	is_selected BOOLEAN NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	optimization_metadata JSON NOT NULL, 
	is_deleted BOOLEAN NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_routes_distance_km CHECK (distance_km >= 0), 
	CONSTRAINT ck_routes_duration_minutes CHECK (duration_minutes >= 0), 
	CONSTRAINT ck_routes_weather_factor CHECK (weather_factor > 0), 
	CONSTRAINT ck_routes_safety_score CHECK (safety_score BETWEEN 0 AND 100), 
	CONSTRAINT ck_routes_status CHECK (status IN ('planned', 'optimized', 'selected', 'completed', 'cancelled')), 
	FOREIGN KEY(shipment_id) REFERENCES shipments (id) ON DELETE CASCADE
)

"""))
    op.execute(sa.text("""

CREATE TABLE waypoints (
	id UUID NOT NULL, 
	route_id UUID NOT NULL, 
	sequence INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	latitude FLOAT NOT NULL, 
	longitude FLOAT NOT NULL, 
	arrival_at TIMESTAMP WITH TIME ZONE, 
	departure_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_waypoints_route_sequence UNIQUE (route_id, sequence), 
	CONSTRAINT ck_waypoints_sequence CHECK (sequence >= 0), 
	CONSTRAINT ck_waypoints_latitude CHECK (latitude BETWEEN -90 AND 90), 
	CONSTRAINT ck_waypoints_longitude CHECK (longitude BETWEEN -180 AND 180), 
	FOREIGN KEY(route_id) REFERENCES routes (id) ON DELETE CASCADE
)

"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_cold_containers_asset_tag ON cold_containers (asset_tag)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_primary_health_centres_code ON primary_health_centres (code)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_primary_health_centres_is_deleted ON primary_health_centres (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_primary_health_centres_name ON primary_health_centres (name)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_roles_is_deleted ON roles (is_deleted)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_roles_name ON roles (name)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_users_email ON users (email)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_users_is_deleted ON users (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_vehicles_type_status ON vehicles (vehicle_type, status)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_vehicles_is_deleted ON vehicles (is_deleted)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_vehicles_registration_number ON vehicles (registration_number)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_warehouses_is_deleted ON warehouses (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_warehouses_name ON warehouses (name)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_warehouses_code ON warehouses (code)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_drivers_name ON drivers (name)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_drivers_license_number ON drivers (license_number)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_drivers_phone ON drivers (phone)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_drivers_is_deleted ON drivers (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_drivers_vehicle_id ON drivers (vehicle_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash)
"""))
    op.execute(sa.text("""
CREATE UNIQUE INDEX ix_shipments_tracking_code ON shipments (tracking_code)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_shipments_is_deleted ON shipments (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_shipments_driver_id ON shipments (driver_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_shipments_container_id ON shipments (container_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_shipments_destination_id ON shipments (destination_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_shipments_warehouse_id ON shipments (warehouse_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_cold_alerts_shipment_id ON cold_alerts (shipment_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_cold_alerts_container_id ON cold_alerts (container_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_predictions_shipment_id ON predictions (shipment_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_routes_shipment_id ON routes (shipment_id)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_routes_is_deleted ON routes (is_deleted)
"""))
    op.execute(sa.text("""
CREATE INDEX ix_waypoints_route_id ON waypoints (route_id)
"""))


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS waypoints CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS routes CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS predictions CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS cold_alerts CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS shipments CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS user_roles CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS refresh_tokens CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS drivers CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS weather_cache CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS warehouses CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS vehicles CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS users CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS roles CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS primary_health_centres CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS cold_containers CASCADE"))
    enum_type = sa.Enum('super_admin', 'admin', 'dispatcher', 'logistics', 'driver', name="user_role")
    enum_type.drop(op.get_bind(), checkfirst=True)
